"""0707 add collumn value to discount table

Revision ID: 414a83ee083b
Revises: e942b3ac895a
Create Date: 2021-07-07 11:10:49.809868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414a83ee083b'
down_revision = 'e942b3ac895a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'value')
    # ### end Alembic commands ###
