"""0716 add slug item

Revision ID: 5a8b533a658d
Revises: c4f00abd5552
Create Date: 2021-07-17 17:24:26.075129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8b533a658d'
down_revision = 'c4f00abd5552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('slug', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'slug')
    # ### end Alembic commands ###
