"""--update Item --add image_url

Revision ID: 74063871f8cc
Revises: fe80f21efd31
Create Date: 2021-06-19 20:56:58.452855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74063871f8cc'
down_revision = 'fe80f21efd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image_url')
    # ### end Alembic commands ###
