"""0628 0 ad code column to order

Revision ID: 76533d76247f
Revises: f8ba62e22a99
Create Date: 2021-06-28 10:28:06.829256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76533d76247f'
down_revision = 'f8ba62e22a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'code')
    # ### end Alembic commands ###
