"""Sec migration

Revision ID: 7aed320d8441
Revises: a6ae0fba9767
Create Date: 2021-06-19 01:32:00.852927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aed320d8441'
down_revision = 'a6ae0fba9767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
