"""0724 update type phone table customers

Revision ID: 7de557f6cf10
Revises: f2d453484ad0
Create Date: 2021-07-24 20:51:13.710879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de557f6cf10'
down_revision = 'f2d453484ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone', type_=sa.BIGINT(), existing_type=sa.INTEGER())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
