"""0627 2 update relation order - orderitem

Revision ID: 88a7ede06255
Revises: e39a92ed5d65
Create Date: 2021-06-27 10:43:46.101650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a7ede06255'
down_revision = 'e39a92ed5d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
