"""0721 add role table 2

Revision ID: 9fcad287e71a
Revises: 529fb454c65d
Create Date: 2021-07-21 15:49:46.438966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcad287e71a'
down_revision = '529fb454c65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'roleId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roleId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_column('roles', 'updated_date')
    op.drop_column('roles', 'created_date')
    # ### end Alembic commands ###
