"""0707 add collumn order

Revision ID: a4e96a33fcf5
Revises: 414a83ee083b
Create Date: 2021-07-07 22:57:26.114660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e96a33fcf5'
down_revision = '414a83ee083b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'total')
    # ### end Alembic commands ###
