"""0724 update code order

Revision ID: b00d57006dac
Revises: e4f2f8d935c2
Create Date: 2021-07-25 09:39:41.765510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00d57006dac'
down_revision = 'e4f2f8d935c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
