"""0707 update customer table

Revision ID: b876b9f170aa
Revises: 23bd44134aad
Create Date: 2021-07-07 09:08:44.862976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b876b9f170aa'
down_revision = '23bd44134aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
