"""0626 1 add relation order -> order_items

Revision ID: be25cbe23db8
Revises: 21bb650ab650
Create Date: 2021-06-26 23:12:58.827333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be25cbe23db8'
down_revision = '21bb650ab650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
