"""0629 0 change code to big int

Revision ID: c13c5fbe5e8f
Revises: d94e2e227243
Create Date: 2021-06-30 00:06:20.205423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13c5fbe5e8f'
down_revision = 'd94e2e227243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
