"""0707 remove tax, and status table order

Revision ID: c4f00abd5552
Revises: a4e96a33fcf5
Create Date: 2021-07-07 23:02:01.020475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f00abd5552'
down_revision = 'a4e96a33fcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'tax')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tax', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
