"""0626 1 update orderItems

Revision ID: cc16d4cdef9b
Revises: be25cbe23db8
Create Date: 2021-06-27 00:45:02.555054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc16d4cdef9b'
down_revision = 'be25cbe23db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_costumber_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'costumber_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('costumber_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_costumber_id_fkey', 'orders', 'customers', ['costumber_id'], ['id'])
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
