"""0629 0 change code to big int

Revision ID: d94e2e227243
Revises: f6e374e4e71b
Create Date: 2021-06-29 23:59:27.509408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94e2e227243'
down_revision = 'f6e374e4e71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
