"""0718 delete stock item

Revision ID: dd000fd5aded
Revises: 5a8b533a658d
Create Date: 2021-07-20 10:22:33.576235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd000fd5aded'
down_revision = '5a8b533a658d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('stock', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
