"""0626 2 update nullable for order - customer_id

Revision ID: e39a92ed5d65
Revises: cc16d4cdef9b
Create Date: 2021-06-27 02:05:03.644770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39a92ed5d65'
down_revision = 'cc16d4cdef9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
