"""0628 0 ad code column to order

Revision ID: f6e374e4e71b
Revises: 76533d76247f
Create Date: 2021-06-28 10:30:16.033702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e374e4e71b'
down_revision = '76533d76247f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
