"""0628 0 refactor model

Revision ID: f8ba62e22a99
Revises: 88a7ede06255
Create Date: 2021-06-28 08:33:59.677784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8ba62e22a99'
down_revision = '88a7ede06255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderitems', 'created_date')
    op.drop_column('orderitems', 'updated_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orderitems', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
